### ISSUE TITLE
Editor Improvements

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#289]
> [<img alt="appinteractive" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-02-26T14:56:36Z" title="Tuesday, February 26th 2019, 3:56:36 pm +01:00">Feb 26, 2019</time>_
_Closed <time datetime="2019-04-03T12:58:26Z" title="Wednesday, April 3rd 2019, 2:58:26 pm +02:00">Apr 3, 2019</time>_
---

Improve the Editor usage (sequel of https://github.com/Human-Connection/Nitro-Web/pull/153)

**Todo`s:**
- [x] edit posts
- [ ] create posts
  - [x] title
  - [x] content
  - [ ] tags
  - [ ] categories
- [x] fix broken integration test as now you cant report your own contributions or your self as a user
- [x] always add `target="_blank"` to the rendered links
- [ ] render all content with the editor-content component
- [ ] **Stylings**
  - [x] bold
  - [x] italic
  - [ ] strike
- [ ] **Elements**
  - [x] links

**Comment by Tirokk** [comment]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-03T12:58:26Z" title="Wednesday, April 3rd 2019, 2:58:26 pm +02:00">Apr 3, 2019</time>_

---


closed in favor of https://github.com/Human-Connection/Human-Connection/issues/379
