### ISSUE TITLE
🌟 [EPIC] User IDs

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#3007]
> [<img alt="alina-beck" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2020-02-05T14:28:18Z" title="Wednesday, February 5th 2020, 3:28:18 pm +01:00">Feb 5, 2020</time>_

---

## 🌟 EPIC
discussed with @DennisHack 

Users should be able to toggle other users' `IDs` on the network, so they can reliably identify them.

### User Problem
At the moment it is quite easy to pose as someone else on Human Connection. This can lead to confusion and can be exploited. A visible unique `user ID` would help to make sure a user really is the one he says he is – we already have these IDs in the database, so this issue is (mainly) about displaying them on the frontend.

### Implementation Step by Step
- [ ] Make IDs short and readable (this will also help with the design): #2786 
- [x] Remove the `hover menu` from the `user teaser`: #3004
- [ ] Add a `toggle ID` button to the `user teaser`: #3005
- [ ] Add a `toggle ID` button to the `user profile`: #3006

### Additional context
The following issues are related but outdated: #252, #2784
The following PR could be used as a basis for updating the `user profile`: #2884

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-05-05T10:58:22Z" title="Tuesday, May 5th 2020, 12:58:22 pm +02:00">May 5, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by ulfgebhardt** [comment]
closing as irrelevant
