### ISSUE TITLE
🔧 [Refactor] Don’t Expose Some Properties Of The Report Node In GraphQL

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#3074]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-02-14T13:55:35Z" title="Friday, February 14th 2020, 2:55:35 pm +01:00">Feb 14, 2020</time>_
_Closed <time datetime="2020-04-04T08:21:28Z" title="Saturday, April 4th 2020, 10:21:28 am +02:00">Apr 4, 2020</time>_
---

## :zap: Refactor ticket

In some cases there is the danger that informations of the `Report` node getting exposed to the frontend. Especially the `filed` property.

### Motive

Security.

### Related issues

None.

### Implementation

- Set permissions in `permissionMiddleware`.
- Write tests for it.

### Todo

- [X] set GQL permission (done by #3075 )
- [x] write tests (done by #3075 )
- [x] refactor now failing tests (done by #3075 )
- [ ] database manipulation to set `Report.disable` to the final decision, last review rules

**Comment by Tirokk** [comment]
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-04-04T08:21:28Z" title="Saturday, April 4th 2020, 10:21:28 am +02:00">Apr 4, 2020</time>_

---


closing this as we are no longer exposing `Report` properties to unauthorized users. See https://github.com/Human-Connection/Human-Connection/pull/3075 
The ToDo to write a database migration has been extracted into its own issue. See https://github.com/Human-Connection/Human-Connection/issues/3412
