### ISSUE TITLE
🐛 [Bug] Editor using LegacyEmbed, only

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#3395]
> [<img alt="rbeer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/rbeer) **Authored by [rbeer](https://github.com/rbeer)**
_<time datetime="2020-04-02T09:53:20Z" title="Thursday, April 2nd 2020, 11:53:20 am +02:00">Apr 2, 2020</time>_

---

## :bug: Bugreport
Editor embeds are being saved in the legacy inline format.
When defining both `Embed` and `LegacyEmbed` in [defaultExtensions.js](https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/Editor/defaultExtensions.js#L40-L53), the latter definition always takes precedence.

The new block level format has therefore been in use for only 6 days ([2019-11-15](https://github.com/Human-Connection/Human-Connection/pull/2242#event-2802905004) - [2019-11-22](https://github.com/Human-Connection/Human-Connection/issues/2259#ref-pullrequest-527155875)).

### Steps to reproduce the behavior
1. Add a comment or post with embed
2. Check `content` field on that `Post`'s query result
3. Embed `<a>` is inline, i.e. inside of `<p>`

### Expected behavior
Embeds' `<a>` are inserted at block-level.

### Timeline
- #1937 reports a bug with hashtags after embeds not being transformed
- #2242 fixes #1937 by changing Embed from inline to block level
- #2259 reports a bug that existing embeds (inline markup in DB) aren't displayed
- #2328 introduces `LegacyEmbed`, which functionally reverts #2242

### Todo
- [ ] ensure paragraphs present above and below embed
  - the embed taking up all the space in the editor view makes it almost impossible to add text, when you paste a video url into an empty editor
- [ ] migrate old posts to new block format
- [ ] fix pasteRule expression ([Appendix B, rfc3986](https://www.ietf.org/rfc/rfc3986.txt))
(merged from #2238)
