### ISSUE TITLE
🌟 [EPIC] Post editor improvements

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#3625]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-06-11T20:35:25Z" title="Thursday, June 11th 2020, 10:35:25 pm +02:00">Jun 11, 2020</time>_

---

## :rocket: Feature

The post editor #328 and #379 has room for improvement. This issue is to collect issues that improve the post editor.

**Bugs**
- [ ] 🐛 Lists in posts and comments are not displayed as lists #3492 
- [ ] 🐛 Editor toolbar on very long articles works not properly #2171 
- [ ] 🐛 Editor using LegacyEmbed, only #3395 
- [ ] 🐛 No warning when leaving the editor accidentally #1858
- [ ] 🐛 Paste in Editor inserts additional Newlines #1856
- [ ] 🐛 Language select looks disabled – but it's not #1467
- [ ] 🐛 Cropping - Save Button hides Wireframe #1952
- [ ] 🐛 Editing posts of Alpha deletes their hashtags #2306
- [ ] 🐛 Invalid HTML for Posts #2056
- [ ] 🐛 Cropping JPG teaser images adds black background #3185
- [ ] 🐛 Post options too small #3186
- [ ] 🐛 comment box disappears while editing comments #3015

**Features**
- [ ] 🚀 Explain Editor Icons with a hover/Mouseover #1950 
- [ ] 🚀 Contributions: Media file upload option #1066 
- [ ] 🚀 I would like to have pictures in the editor #3158 
- [ ] 💬 [Question] Do we want an image button for the editor? #1472  
- [ ] 🚀 Remove 'Carriage Return' within marked text sections #2920 
- [ ] 🚀 Create the teaser image from the metadata of a pasted link(->embed) #1200 
- [ ] 🚀 Show supported image formats in editor #1949
- [ ] 🚀 Highlight create post button #2783
- [ ] 🚀 Toolbar always visible when editing posts and comments #3626
- [ ] 🚀 Editor toolbar: Add keyboard shortcut and markdown to link button #3627
- [ ] 🚀 Increase margin of headings and rulers #3628
- [ ] 🚀 Input field for tags #2196
- [ ] 🚀 Improved editor layout for small screens #3629
- [ ] 🌟 Accessibility #3633 
- [ ] 🚀 mention user list - show comments participants first #3738

### User Problem

The post editor is very often used by users. Every improvement to the editor increases efficiency for and happiness of the users.

### Implementation

Fix the bugs first. Prioritize feature requests, then start working on it.

### Additional context

As discussed with @Raimundo-dev today.
