### ISSUE TITLE
🌟 [EPIC] User Dashboard / Home

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#372]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-03T10:37:29Z" title="Wednesday, April 3rd 2019, 12:37:29 pm +02:00">Apr 3, 2019</time>_
_Closed <time datetime="2019-12-19T21:14:24Z" title="Thursday, December 19th 2019, 10:14:24 pm +01:00">Dec 19, 2019</time>_
---

### User Dashboard / Home

![image](https://user-images.githubusercontent.com/1238238/55469422-c7e4da00-5605-11e9-93dd-71c0e960a211.png)

Header:
- [X] GoToFeed
- [ ] Search https://github.com/Human-Connection/Human-Connection/issues/308
- [ ] Filter https://github.com/Human-Connection/Human-Connection/issues/374
- [X] Language
- [x] Notifications https://github.com/Human-Connection/Human-Connection/issues/345
- [X] Usermenu
- [ ] Sorting https://github.com/Human-Connection/Human-Connection/issues/375

Post Card:
- [x] Author Bug https://github.com/Human-Connection/Human-Connection/issues/376
- [X] CreatedAt
- [X] Title
- [X] Content Excerpt
- [X] Categories
- [X] Actions
- [x] Design differences https://github.com/Human-Connection/Human-Connection/issues/377
- [ ] Dynamic Card Height https://github.com/Human-Connection/Human-Connection/issues/378

More:
- [ ] New Post https://github.com/Human-Connection/Human-Connection/issues/379 + ~~Bug~~ https://github.com/Human-Connection/Human-Connection/issues/337
- [ ] Footer https://github.com/Human-Connection/Human-Connection/issues/381

### Userstory

```gherkin
Feature: News Feed
  As a user
  I want to see a list of contributions, possibly filtered and sorted,
  In order to get interesting news and ideas and get possibly involved in candos and projects.
```

### Design & Layout - Vision
![image](https://user-images.githubusercontent.com/1238238/55667309-ee4f8300-585a-11e9-945d-ecbdaf47ebca.png)

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55667323-25be2f80-585b-11e9-92f3-2a86cf685b1c.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55472317-18f7cc80-560c-11e9-80cf-962c81383c1b.png)

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2019-11-19T21:10:08Z" title="Tuesday, November 19th 2019, 10:10:08 pm +01:00">Nov 19, 2019</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
