### ISSUE TITLE
🚀 [Feature] Filter

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#374]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-03T11:08:29Z" title="Wednesday, April 3rd 2019, 1:08:29 pm +02:00">Apr 3, 2019</time>_
_Closed <time datetime="2020-02-11T13:02:24Z" title="Tuesday, February 11th 2020, 2:02:24 pm +01:00">Feb 11, 2020</time>_
---

### Filter
![image](https://user-images.githubusercontent.com/1238238/55473778-c5877d80-560f-11e9-9999-26542d2d4982.png)

- [x] Categories https://github.com/Human-Connection/Human-Connection/issues/967
- [x] Emotions - depends on https://github.com/Human-Connection/Human-Connection/issues/384
- [ ] Group Emoticons in 3 categories [Positive, Other, Netagive]
- [ ] No Filter selected = empty Page
- [ ] Filter for Post Type
- [ ] Default Filter ( Happy )
- [ ] Persisten Filter-Settings per User
- [ ] (optional) Recheck Usability when clicking one icon deselect it (seems not the thing I expect when clicking) Talk to @ulfgebhardt when you implement this
- [ ] (optional) Rethink the Design an pack the Filter in a better way
- [ ] Filter by user type (source): **All** or **connections** (friends), additional to followers

Regarding Emoticons
```
Sort and devide them into 3 categories (Filter): 

POSITIVE: Heart (1), happy (2), funny (3)

OTHER: suprised (4), questioning (5)

NEGATIVE: Broken Heart (Heart broken) (6), cry/sad (7), angry (8), help! (blue siren on head) (9), fear (10) 
```

### Userstory Categories
```
As a network user
I'd like to filter posts by categories
E.g. when I am only interested in political content or not interested in religous content
```

### Userstory Emotions
```
As a user
I'd like to filter posts by emotions
E.g. when I am not in the mood for sad or upsetting content
```

### Design & Layout - Vision

![image](https://user-images.githubusercontent.com/1238238/55667303-bc3e2100-585a-11e9-99c6-285a75ddcd94.png)

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55474056-873e8e00-5610-11e9-8493-9962754d99c5.png)

Click on Sub-Icon - disables (check if thats a good aproach)
![image](https://user-images.githubusercontent.com/1238238/55474079-97566d80-5610-11e9-8755-aed8225ee88d.png)

Click on All-Icon (if all are selected -> all deselected; if not all are selected -> all selected)
![image](https://user-images.githubusercontent.com/1238238/55474137-bd7c0d80-5610-11e9-8502-dd52383b7989.png)
![image](https://user-images.githubusercontent.com/1238238/55667341-65851700-585b-11e9-9d63-dbdf3e3c19c9.png)

### Design & Layout - Nitro

Missing

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2020-01-12T12:39:33Z" title="Sunday, January 12th 2020, 1:39:33 pm +01:00">Jan 12, 2020</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
