### ISSUE TITLE
🌟 [EPIC] User Profile

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#395]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-04T09:57:59Z" title="Thursday, April 4th 2019, 11:57:59 am +02:00">Apr 4, 2019</time>_
_Closed <time datetime="2019-12-19T21:14:27Z" title="Thursday, December 19th 2019, 10:14:27 pm +01:00">Dec 19, 2019</time>_
---

### User Profile

![image](https://user-images.githubusercontent.com/1238238/55546954-938a2000-56d0-11e9-8de8-24d30cdb9eaa.png)

- [ ] (optional) Header Image + Upload https://github.com/Human-Connection/Human-Connection/issues/397
- [X] UserImage
- [x] UserImage Upload https://github.com/Human-Connection/Human-Connection/issues/399
- [X] Username
- [X] (optional) Access Settings from Profile as Owner https://github.com/Human-Connection/Human-Connection/issues/400

Contributions:
- [X] Contribution Count
- [X] Comments Count
- [X] Shouts Count

Network:
- [ ] (optional) User follows NGOs Count @appinteractive What is a NGO Database wise - an user, an orga?
- [X] User follows People Count @appinteractive Can we rename "Folgen" into "Followers"? makes sense?
- [ ] (optional) User follows Projects Count @appinteractive What is a Project Database wise - an user, an orga?

(optional) Being Active/CanDos:
- [ ] (optional) CanDo Commitment Count
- [ ] (optional) CanDo Completed Count
- [ ] (optional) List of CanDo's participated in

Posts:
- [ ] (optional) Question "What are your Plans for Today $username?" @appinteractive @dennishack Whats the stance here?
- [X] Create Post Button
- [X] Posts done cronologically

Comments:
- [x] Tab not implemented https://github.com/Human-Connection/Human-Connection/issues/401

Shouts:
- [x] Tab not implemented https://github.com/Human-Connection/Human-Connection/issues/402

### Userstory
```
Feature: User Profile
  As a user
  I want to show personal information to other users in my profile
  In order to tell about me and get in contact with them.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55547043-c502eb80-56d0-11e9-82f0-b2ebfc167fd2.png)
![image](https://user-images.githubusercontent.com/1238238/55547086-dcda6f80-56d0-11e9-8178-c798128ab97e.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55556251-609f5680-56e7-11e9-85bc-31dfc389c8d7.png)

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2019-11-19T21:10:05Z" title="Tuesday, November 19th 2019, 10:10:05 pm +01:00">Nov 19, 2019</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
