### ISSUE TITLE
🌟 [EPIC] Security / Privacy

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#426]
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-05T11:44:40Z" title="Friday, April 5th 2019, 1:44:40 pm +02:00">Apr 5, 2019</time>_
_Closed <time datetime="2019-12-19T21:14:29Z" title="Thursday, December 19th 2019, 10:14:29 pm +01:00">Dec 19, 2019</time>_
---

### Security / Privacy

- [x] [Bug] Don't expose private RSA key https://github.com/Human-Connection/Human-Connection/issues/411
- [ ] Checklist ExpressJS Security Best Practices https://github.com/human-connection/human-connection/issues/203
- [ ] Sanitize Input to prevent Injection https://github.com/human-connection/human-connection/issues/204
- [x] Multiple user login https://github.com/human-connection/human-connection/issues/208
- [x] 🐛 Whitelist all auto-generated Mutations/Queries https://github.com/human-connection/human-connection/issues/343

### Additional context

Rised Questions:
- Are the automatically generated mutations a security risk? ( @Tirokk )
  - They are not handled yet by the permissions middleware.
  - Should we whitelist the mutations in general which are handled by the permissions middleware? So all other mutations, not checked for security, are automatically blacklisted …

**Comment by Tirokk** [comment]
> [<img alt="stale[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/stale) **Authored by [stale[bot]](https://github.com/apps/stale)**
_<time datetime="2019-11-19T21:10:03Z" title="Tuesday, November 19th 2019, 10:10:03 pm +01:00">Nov 19, 2019</time>_

---


This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
